version: '3' # version of docker-compose to use
services:
  alltube:
    image: rudloff/alltube:latest
    restart: unless-stopped
    expose:
      - 80
    environment:
      - TZ=${MY_TZ:-SUBFAIL}
      - VIRTUAL_HOST=alltube.${DNS_SUFFIX:-local}
      - LETSENCRYPT_HOST=alltube.${DNS_SUFFIX:-local}
      - LETSENCRYPT_EMAIL=${LETS_ENC_EMAIL:-SUBFAIL}
    networks:
      - reverse-proxy
    labels:
      - "container_group=youtube"
      - "traefik.enable=true"

      - "traefik.docker.network=reverse-proxy" #needed if there are multiple networks attached to this container
      - "traefik.http.services.alltube.loadbalancer.server.port=8384" #needed if multiple ports are exposed

      - "traefik.http.routers.alltube.tls=true"
      - "traefik.http.routers.alltube.rule=Host(`alltube.${DNS_SUFFIX:-local}`)"
      - "traefik.http.routers.alltube.middlewares=middlewares-secured-oauth"
      - "traefik.http.routers.alltube.entrypoints=websecure"
      - "traefik.http.routers.alltube.tls.certresolver=myresolver"
  youtube-dl:
    image: gitterdone/youtube-dl-webui:latest
    restart: always
    expose:
      - 8282
    environment:
      - DL_VIDEO_PATH=/video/
      - TZ=${MY_TZ:-SUBFAIL}
      - VIRTUAL_HOST=youtubedl.${DNS_SUFFIX:-local}
      - LETSENCRYPT_HOST=youtubedl.${DNS_SUFFIX:-local}
      - LETSENCRYPT_EMAIL=${LETS_ENC_EMAIL:-SUBFAIL}
    volumes:
      - youtube_video:/root/output:nocopy
    networks:
      - reverse-proxy
    labels:
      - "container_group=youtube"
      - "traefik.enable=true"

      - "traefik.docker.network=reverse-proxy" #needed if there are multiple networks attached to this container
      - "traefik.http.services.youtubedl.loadbalancer.server.port=8384" #needed if multiple ports are exposed

      - "traefik.http.routers.youtubedl.tls=true"
      - "traefik.http.routers.youtubedl.rule=Host(`youtubedl.${DNS_SUFFIX:-local}`)"
      - "traefik.http.routers.youtubedl.middlewares=middlewares-secured-oauth"
      - "traefik.http.routers.youtubedl.entrypoints=websecure"
      - "traefik.http.routers.youtubedl.tls.certresolver=myresolver"

volumes:
  youtube_video:
    driver: "local"
    driver_opts:
      device: ":${NAS_BASE_PATH:-SUBFAIL}/video/youtube"
      type: nfs
      o: addr=${NAS_ADDR:-SUBFAIL},rw,vers=4

  youtube_music:
    driver: "local"
    driver_opts:
      device: ":${NAS_BASE_PATH:-SUBFAIL}/music/ripped_from_video"
      type: nfs
      o: addr=${NAS_ADDR:-SUBFAIL},rw,vers=4


networks:
  reverse-proxy:
    external:
      name: reverse-proxy

