version: '3'

services:
  bitwarden:
    image: vaultwarden/server:1.29.0
    restart: unless-stopped
    volumes:
      - bitwarden_data:/data
    environment:
      - "SIGNUPS_ALLOWED=false"   # set to false to disable signups
#      - "ADMIN_TOKEN="
      - "DOMAIN=https://vault.${DNS_SUFFIX:-local}"
      - "SMTP_HOST=${SENDGRID_SMTP_HOST:-SUBFAIL}"
      - "SMTP_PORT=${SENDGRID_SMTP_PORT:-SUBFAIL}"
      - "SMTP_SECURITY=force_tls"
      - "SMTP_USERNAME=apikey"
      - "SMTP_PASSWORD=${SENDGRID_API_KEY:-SUBFAIL}"
      - "SMTP_AUTH_MECHANISM='Login'"
      - "SMTP_FROM=${SENDGRID_FROM_EMAIL:-SUBFAIL}"

    networks:
      - reverse-proxy
    labels:
      - "container_group=bitwarden"
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy" #needed if there are multiple networks attached to this container
      - "traefik.http.routers.vault.tls.certresolver=myresolver"
      - "traefik.http.routers.vault.rule=Host(`vault.${DNS_SUFFIX:-local}`)"
      - "traefik.http.routers.vault.entrypoints=websecure"

volumes:
  bitwarden_data:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/bitwarden"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}


networks:
  reverse-proxy:
    external: true
