version: '3'

services:
  bitwarden:
    image: bitwardenrs/server
    restart: unless-stopped
    volumes:
      - bitwarden_data:/data
    environment:
      - "VIRTUAL_PORT=80"
      - "VIRTUAL_HOST=vault.${DNS_SUFFIX:-local}"
      - "LETSENCRYPT_HOST=vault.${DNS_SUFFIX:-local}"
      - "LETSENCRYPT_EMAIL=${LETS_ENC_EMAIL:-SUBFAIL}"
      - "WEBSOCKET_ENABLED=true" # Required to use websockets
      - "SIGNUPS_ALLOWED=true"   # set to false to disable signups
#      - "ADMIN_TOKEN="
      - "DOMAIN=https://vault.${DNS_SUFFIX:-local}"
      - "SMTP_HOST=smtp"
      - "SMTP_FROM=bitwarden@noreply.com"
      - "SMTP_PORT=25"
      - "SMTP_SSL=false"
    env_file:
      - .env
    networks:
      - reverse-proxy
      - smtp

volumes:
  bitwarden_data:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/bitwarden"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}


networks:
  reverse-proxy:
    external: true
  smtp:
    external: true
