version: '3.2'
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    environment:
      PLAYWRIGHT_DRIVER_URL: "ws://playwright-chrome:3000/chrome?blockAds=false&launch=eyJoZWFkbGVzcyI6ZmFsc2UsInN0ZWFsdGgiOnRydWUsImFyZ3MiOlsiLS13aW5kb3ctc2l6ZT0xOTIwLDEwODAiLCItLW5vLXNhbmRib3giLCItLWRpc2FibGUtZGV2LXNobS11c2FnZSJdfQ==" #launch string: {"headless":false,"stealth":true,"args":["--window-size=1920,1080","--no-sandbox","--disable-dev-shm-usage"]}
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - changedetection-data:/datastore:rw

  playwright-chrome:
    image: ghcr.io/browserless/chrome
    hostname: playwright-chrome
    environment:
      TIMEOUT: "300000"
      CONCURRENT: "10"
    restart: unless-stopped
 
networks:
  reverse-proxy:
    external: true

volumes:
  changedetection-data:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX:-SUBFAIL}/containers/changedetection"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}  