version: '3' # version of docker-compose to use
services:
  hub-mirror:
    image: registry
    restart: always
    ports:
      - 5000:5000
    volumes:
      - registry_config:/etc/docker/registry
      - registry_cache:/var/lib/registry
          labels:
    container_group: registry
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS:-SUBFAIL}
        labels: container_group

volumes:
  registry_config:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/registry/config"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}

  registry_cache:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/registry/cache"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
