version: '2.2'

services:
#  minecraft1:
#    ports:
#      - "25565:25565"
#    image: itzg/minecraft-server
#    container_name: minecraft1
#    restart: always
#    volumes:
#      - minecraft1_data:/data
#    environment:
#      - EULA=TRUE
#      - VERSION=1.13.2
#      - ONLINE_MODE=FALSE
#      - MODE=creative
#      - OPS=c,b
#    labels:
#      container_group: minecraft

  minecraft2:
#    ports:
#      - "25566:25565"
    expose:
      - "25565"

    image: itzg/minecraft-server
    container_name: minecraft2
    restart: unless-stopped
    volumes:
      - minecraft2_data:/data
    environment:
      - EULA=TRUE
      - VERSION=1.13.2
      - ONLINE_MODE=FALSE
      - TYPE=SPIGOT
      - SPIGOT_DOWNLOAD_URL=https://cdn.getbukkit.org/spigot/spigot-1.13.2.jar
      - MAX_MEMORY=2G
      - MAX_BUILD_HEIGHT=1000
      - WHITELIST=cody,brooke,dad,alex,taylor
      - OPS=cody,brooke,dad,alex,taylor
      - MODE=creative
#      - WORLD=
#      - MODPACK=
    networks:
      - reverse-proxy
    labels:
      - "container_group=minecraft"

      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy" #needed if there are multiple networks attached to this container
      
      #tcp 
      - "traefik.tcp.routers.minecraft2.entrypoints=minecraft"
      - "traefik.tcp.routers.minecraft2.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.minecraft2.service=minecraft2"
      - "traefik.tcp.routers.minecraft2.tls=false"
      - "traefik.tcp.services.minecraft2.loadbalancer.server.port=25565"
networks:
  reverse-proxy:
    external:
      name: reverse-proxy

volumes:
  minecraft1_data:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/minecraft/data"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}

  minecraft2_data:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/minecraft/data2"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}

