version: "3"
services:
  classifiedscraper:
    image: "gitterdone/classifiedscraper:latest"
    restart: unless-stopped
    volumes:
      - classified_data:/usr/src/app/data
    environment:
      - TZ=${MY_TZ:-SUBFAIL}
      - CLASSIFIEDSCRAPER_DISCORD_NOTIFICATION_URL=${SCRAPY_DISCORD_NOTIFICATION_URL:-SUBFAIL}
      - EBAY_APP_ID=${EBAY_APP_ID:-SUBFAIL}
    labels:
      - "com.centurylinklabs.watchtower.scope=mydev"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --scope mydev
    environment:
      - WATCHTOWER_POLL_INTERVAL=900
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL:-SUBFAIL}
  
volumes:
  classified_data:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/classified"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
