version: "2.2"
services:
  nginx-proxy:
    image: nginx
    restart: unless-stopped
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-ssl:/etc/nginx/certs:ro
      - nginx-htpasswd:/etc/nginx/htpasswd
    labels:
      container_group: proxy
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
      co.elastic.logs/module: nginx
      co.elastic.logs/fileset.stdout: access
      co.elastic.logs/fileset.stderr: error
    networks:
      - reverse-proxy

  nginx-gen:
    image: jwilder/docker-gen:0.7.3
    restart: unless-stopped
    container_name: nginx-gen
    command: -notify-sighup nginx-proxy -wait 5s:30s -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-gen-templates:/etc/docker-gen/templates:rw
      - nginx-ssl:/etc/nginx/certs:ro
    links:
      - nginx-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen: "true"
      container_group: proxy
    environment:
      - DEFAULT_HOST=${DEFAULT_HOST:-SUBFAIL}
    networks:
      - reverse-proxy

  nginx-ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12.1
    restart: unless-stopped
    container_name: nginx-ssl
    depends_on:
      - nginx-proxy
      - nginx-gen
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - ./nginx:/etc/docker-gen/templates:ro
      - nginx-ssl:/etc/nginx/certs:rw
    environment:
      #- ACME_CA_URI
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEBUG=false
    links:
      - nginx-proxy
      - nginx-gen
    networks:
      - reverse-proxy
    labels:
      container_group: proxy

networks:
  reverse-proxy:
    external: true

volumes:
  nginx-conf:
  nginx-vhost:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/nginx/vhostd"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}

  nginx-html:

  nginx-ssl:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/nginx/certs"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}

  nginx-htpasswd:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/nginx/htpasswd"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}

  nginx-gen-templates:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/nginx-proxy"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
