version: '3'
services:
  openvpn_udp:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn_udp
    entrypoint: ["ovpn_run", "--config", "/etc/openvpn/openvpn_udp.conf"]
    expose:
     - "1194/udp"
    restart: unless-stopped
    volumes:
#     - ./openvpn-data/conf:/etc/openvpn
      - openvpn_data:/etc/openvpn
    dns:
      - 172.68.0.101
    networks:
      pihole_sub:
      reverse-proxy:
    labels:
      - "container_group=vpn"
      - "traefik.enable=true"

      - "traefik.docker.network=reverse-proxy" #needed if there are multiple networks attached to this container
      
      #udp 
      - "traefik.udp.routers.openvpn.entrypoints=openvpn_udp"
      - "traefik.udp.routers.openvpn.service=openvpn"
      - "traefik.udp.services.openvpn.loadbalancer.server.port=1194"

  openvpn_tcp:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn_tcp
    entrypoint: ["ovpn_run", "--config", "/etc/openvpn/openvpn_tcp.conf"]
    expose:
     - "443"
    restart: always
    volumes:
     # - ./openvpn-data/conf:/etc/openvpn
     - openvpn_data:/etc/openvpn
    dns:
      - 172.68.0.101
    networks:
      pihole_sub:
      reverse-proxy:
    labels:
      - "container_group=vpn"
      - "traefik.enable=true"

      - "traefik.docker.network=reverse-proxy" #needed if there are multiple networks attached to this container
      
      #tcp 
      - "traefik.tcp.routers.openvpn.entrypoints=websecure"
      - "traefik.tcp.routers.openvpn.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.openvpn.service=openvpn"
      - "traefik.tcp.routers.openvpn.tls=false"
      - "traefik.tcp.services.openvpn.loadbalancer.server.port=443"
    
  pihole_openvpn:
    image: pihole/pihole:latest
    restart: always
    container_name: pihole
    expose:
      - "80"
      - "443"
      - "53/tcp"
      - "53/udp"
    volumes:
      - pihole_data:/etc/pihole
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      TZ: ${MY_TZ:-SUBFAIL}
#      - WEBPASSWORD=${PIHOLE_WEBPASS:-SUBFAIL}
    networks:
      pihole_sub:
        ipv4_address: 172.68.0.101
#      default: #this breaks return routing to openvpn

networks:
  pihole_sub:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.68.0.0/16
  reverse-proxy:
    external: true

volumes:
  openvpn_data:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/openvpn"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}

  pihole_data:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/pihole"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
