version: '3' # version of docker-compose to use
services:
  phlex:
    image: digitalhigh/flextv:latest
    privileged: true
    restart: always
    expose:
      - 5666
    environment:
      - TZ=${MY_TZ:-SUBFAIL}
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=phlex.${DNS_SUFFIX:-local}
      - LETSENCRYPT_HOST=phlex.${DNS_SUFFIX:-local}
      - LETSENCRYPT_EMAIL=${LETS_ENC_EMAIL:-SUBFAIL}
    volumes:
      - phlex_config:/config
    networks:
      - reverse-proxy
    labels:
      - "container_group=sync"
      - "traefik.enable=true"

      - "traefik.docker.network=reverse-proxy" #needed if there are multiple networks attached to this container
      - "traefik.http.services.phlex.loadbalancer.server.port=8384" #needed if multiple ports are exposed

      # internal route for internal ips
      - "traefik.http.routers.phlex2.tls=true"
      - "traefik.http.routers.phlex2.tls.certresolver=myresolver"
      - "traefik.http.routers.phlex2.rule=Host(`phlex.${DNS_SUFFIX:-local}`) && HeadersRegexp(`X-Real-Ip`, `${TRAEFIK_INTERNAL_IPS:-SUBFAIL}`)"
      - "traefik.http.routers.phlex2.priority=100"
      - "traefik.http.routers.phlex2.entrypoints=websecure"
      # default route for external basic auth
      - "traefik.http.routers.phlex.tls=true"
      - "traefik.http.routers.phlex.rule=Host(`phlex.${DNS_SUFFIX:-local}`)"
      - "traefik.http.routers.phlex.priority=90"
      - "traefik.http.routers.phlex.middlewares=myauth"
      - "traefik.http.routers.phlex.entrypoints=websecure"
      - "traefik.http.routers.phlex.tls.certresolver=myresolver"
volumes:
  phlex_config:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/phlex"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
