version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole2
    domainname: ${DNS_SUFFIX:-local}
    restart: unless-stopped
    cap_add:
     - NET_ADMIN
    ports:
      - 22/tcp #gravity sync
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp # Only required if you are using Pi-hole as your DHCP server
      - 80/tcp
    expose:
      - "80"
      - "53/tcp"
      - "53/udp"
#    volumes:
#      - pihole-config:/etc/pihole
# wouldn't start without dns settings
    dns:
       - 127.0.0.1
       - 1.1.1.1
    environment:
      - IPv6=false
      - DNSMASQ_LISTENING=all
      - FTLCONF_LOCAL_IPV4=192.168.3.3
      - TZ=${MY_TZ:-SUBFAIL}
      - WEBPASSWORD=${PIHOLE_WEBPASS:-SUBFAIL}
      - PIHOLE_DNS_=1.1.1.1;8.8.8.8;6.6.6.6
      - DHCP_ACTIVE=true
      - DHCP_START=192.168.3.201
      - DHCP_END=192.168.3.240
      - DHCP_ROUTER=192.168.3.1
      - DHCP_LEASETIME=2
      - PIHOLE_DOMAIN=${DNS_SUFFIX:-local}
      - QUERY_LOGGING=false
    
    networks:
      pihole_network:
        ipv4_address: 192.168.3.3  
#      - reverse-proxy

    labels:
      - "container_group=dns"
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy" #needed if there are multiple networks attached to this container
      - "traefik.http.services.pihole.loadbalancer.server.port=80" #needed if multiple ports are exposed
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.${DNS_SUFFIX:-local}`)"
      - "traefik.http.routers.pihole.middlewares=middlewares-secured-oauth,add-pihole"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls.certresolver=myresolver"
      - "traefik.http.middlewares.add-pihole.addPrefix.prefix=/admin"

      #tcp 
      - "traefik.tcp.routers.pihole.entrypoints=dns"
      - "traefik.tcp.routers.pihole.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.pihole.service=pihole"
      - "traefik.tcp.routers.pihole.tls=false"
      - "traefik.tcp.services.pihole.loadbalancer.server.port=53"
      #udp 
      - "traefik.udp.routers.pihole.entrypoints=dns_udp"
      - "traefik.udp.routers.pihole.service=pihole"
      - "traefik.udp.services.pihole.loadbalancer.server.port=53"

networks:
  # reverse-proxy:
  #   external: true
  # back:
  #   driver: bridge
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.3.0/24            
          gateway: 192.168.3.1              # <-- Update
#          ip_range: 192.168.123.192/28        # <-- Update

volumes:
  pihole-config:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/pihole/config"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}

