version: "3"

services:
  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
#   possibly needed for DHCP server
    cap_add:
     - NET_ADMIN
 #   ports:
 #     - "53:53/tcp"
 #     - "53:53/udp"
 #     - "8095:80"
    expose:
      - "80"
      - "53/tcp"
      - "53/udp"
#    volumes:
#      - pihole-config:/etc/pihole
# only needed for custom dnsmasque settings
#      - pihole-dnsmasq:/etc/dnsmasq.d
# wouldn't start without dns settings
#    dns:
#       - 127.0.0.1
#       - 192.168.0.254
    environment:
#      - IPv6=False
#      - DNSMASQ_LISTENING=all
#      - ServerIP=${HOST_IP:-SUBFAIL}
      - HTTPS_METHOD=noredirect
      - VIRTUAL_HOST=pihole.${DNS_SUFFIX:-local}
      - LETSENCRYPT_HOST=pihole.${DNS_SUFFIX:-local}
      - LETSENCRYPT_EMAIL=${LETS_ENC_EMAIL:-SUBFAIL}
      - TZ=${MY_TZ:-SUBFAIL}
      - WEBPASSWORD=${PIHOLE_WEBPASS:-SUBFAIL}
    networks:
      - reverse-proxy
    #  - back #multiple networks breaks traefik routing
    labels:
      - "container_group=dns"
      - "traefik.enable=true"

      - "traefik.docker.network=reverse-proxy" #needed if there are multiple networks attached to this container
      - "traefik.http.services.pihole.loadbalancer.server.port=80" #needed if multiple ports are exposed

      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.${DNS_SUFFIX:-local}`)"
      - "traefik.http.routers.pihole.middlewares=middlewares-secured-oauth,add-pihole"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls.certresolver=myresolver"

      - "traefik.http.middlewares.add-pihole.addPrefix.prefix=/admin"


      #tcp 
      - "traefik.tcp.routers.pihole.entrypoints=dns"
      - "traefik.tcp.routers.pihole.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.pihole.service=pihole"
      - "traefik.tcp.routers.pihole.tls=false"
      - "traefik.tcp.services.pihole.loadbalancer.server.port=53"
      #udp 
      - "traefik.udp.routers.pihole.entrypoints=dns_udp"
      - "traefik.udp.routers.pihole.service=pihole"
      - "traefik.udp.services.pihole.loadbalancer.server.port=53"




  pihole-exporter:
    image: ekofr/pihole-exporter:latest
    restart: always
    ports:
      - 9311:9311/tcp
    environment:
      - PIHOLE_HOSTNAME=pihole
      - PIHOLE_PASSWORD=${PIHOLE_WEBPASS:-local}
    networks:
      - reverse-proxy
#      - monitoring_logging    

networks:
  reverse-proxy:
    external: true
  back:
    driver: bridge
  monitoring_logging:
    external: true

volumes:
  pihole-config:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/pihole/config"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}

  pihole-dnsmasq:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/pihole/dnsmasq.d"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
