version: "3"

services:
  pihole:
    image: diginc/pi-hole:latest
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    expose:
      - "80"
    volumes:
      - pihole-config:/etc/pihole
      - pihole-dnsmasq:/etc/dnsmasq.d
    environment:
      - ServerIP=${HOST_IP:-SUBFAIL}
      - HTTPS_METHOD=noredirect
      - VIRTUAL_HOST=pihole.${DNS_SUFFIX:-local}
      - LETSENCRYPT_HOST=pihole.${DNS_SUFFIX:-local}
      - LETSENCRYPT_EMAIL=${LETS_ENC_EMAIL:-SUBFAIL}
      - TZ=${MY_TZ:-SUBFAIL}
      - WEBPASSWORD=${PIHOLE_WEBPASS:-SUBFAIL}
    networks:
      - reverse-proxy
    labels:
      container_group: dns
    logging:
      driver: gelf
      options:
        gelf-address: ${GELF_ADDRESS:-SUBFAIL}
        labels: container_group

networks:
  reverse-proxy:
    external: true

volumes:
  pihole-config:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/pihole/config"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}

  pihole-dnsmasq:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/pihole/dnsmasq.d"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
