version: '2.2'
services:
  plex:
    image: plexinc/pms-docker:latest
    restart: unless-stopped
#    ports:
#     - 32400:32400 #plex web
#     - 33400:33400 #insecure web tools
    expose:
     - 32400
    volumes:
#     - plex_config:/config
     - plex_config_local:/config
     - plex_config:/mnt/plex_config_remote
     - plex_config_local:/mnt/plex_config_local
     - /tmp:/transcode #transcoode to memory
#     - plex_transcode:/transcode
     - audiobooks:/mnt/audiobooks
     - scratch:/mnt/scratch
     - music:/mnt/music
     - video:/mnt/video
#     - /opt/containerlogs/plex:/config/Library/Application Support/Plex Media Server/Logs #expose the logs to the host for Filebeat - causes permission errors when owned by root
    environment:
     - PLEX_GID=1001
     - PLEX_UID=1000
     - CHANGE_CONFIG_DIR_OWNERSHIP=true
#     - PLEX_MEDIA_SERVER_USE_SYSLOG=true
     - HTTPS_METHOD=noredirect #older devices can't do TLS
     - VIRTUAL_PORT=32400
#     - PLEX_CLAIM= #valid for 5 minutes
     - TZ=${MY_TZ:-SUBFAIL}
     - VIRTUAL_HOST=plex.${DNS_SUFFIX:-local}
     - LETSENCRYPT_HOST=plex.${DNS_SUFFIX:-local}
     - LETSENCRYPT_EMAIL=${LETS_ENC_EMAIL:-SUBFAIL}
    networks:
      - reverse-proxy
#    cpu_percent: 30 #limit cpu usage percentage
#    cpus: 1.0 #limit to x cpu
    labels:
      - "container_group=plex"

      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy" #needed if there are multiple networks attached to this container
      - "traefik.http.services.plex.loadbalancer.server.port=32400" #needed if multiple ports are exposed
      - "traefik.http.routers.plex.tls.certresolver=myresolver"
      - "traefik.http.routers.plex.rule=Host(`plex.${DNS_SUFFIX:-local}`)"
      - "traefik.http.routers.plex.entrypoints=websecure"

networks:
  reverse-proxy:
    external: true

volumes:
  plex_config:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/plex/config"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
  plex_config_local:
    driver: "local"
    driver_opts:
      device: "/opt/plex_config_local"
      type: none
      o: bind

  plex_transcode:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/plex/transcode"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
  scratch:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX:-SUBFAIL}/scratch"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
  music:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX:-SUBFAIL}/music"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
  video:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX:-SUBFAIL}/video"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
  audiobooks:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX:-SUBFAIL}/books/Audio books"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
