version: "3"
services:
  smokeping:
    image: linuxserver/smokeping
    restart: unless-stopped
    container_name: smokeping
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=${MY_TZ:-SUBFAIL}
      - VIRTUAL_HOST=smokeping.${DNS_SUFFIX:-local}
      - LETSENCRYPT_HOST=smokeping.${DNS_SUFFIX:-local}
      - LETSENCRYPT_EMAIL=${LETS_ENC_EMAIL:-SUBFAIL}
    volumes:
      - smokeping_config:/config
      - smokeping_data:/data
    expose:
      - 80
    restart: unless-stopped
    networks:
      - reverse-proxy
    labels:
      container_group: monitoring

networks:
  reverse-proxy:
    external: true


volumes:
  smokeping_config:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/smokeping/config"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}

  smokeping_data:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/smokeping/data"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
