version: '2.2'
services:
  syncthing:
    image: linuxserver/syncthing:version-v1.12.0
    restart: unless-stopped
    ports:
     - 22000:22000 #
     - 21027:21027/udp #
    expose:
     - 8384
    volumes:
     - syncthing_config:/config
     - syncthing_books:/mnt/books
     - syncthing_scratch:/mnt/scratch
     - syncthing_music:/mnt/music
     - syncthing_video:/mnt/video
     - syncthing_camelot:/mnt/camelot
     - syncthing_pictures:/mnt/pictures
     - syncthing_data:/mnt/data
     - syncthing_home:/mnt/home
     - syncthing_bitwarden:/mnt/bitwarden
    environment:
     - PGID=1001
     - PUID=0
     - UMASK_SET=002
     - VIRTUAL_PORT=8384
     - TZ=${MY_TZ:-SUBFAIL}
     - VIRTUAL_HOST=syncthing.${DNS_SUFFIX:-local}
     - LETSENCRYPT_HOST=syncthing.${DNS_SUFFIX:-local}
     - LETSENCRYPT_EMAIL=${LETS_ENC_EMAIL:-SUBFAIL}
    networks:
      - reverse-proxy
    labels:
      - "container_group=sync"
      - "traefik.enable=true"

      - "traefik.docker.network=reverse-proxy" #needed if there are multiple networks attached to this container
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384" #needed if multiple ports are exposed

      - "traefik.http.routers.syncthing.tls=true"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.${DNS_SUFFIX:-local}`)"
      - "traefik.http.routers.syncthing.middlewares=middlewares-secured-oauth"
      - "traefik.http.routers.syncthing.entrypoints=websecure"
      - "traefik.http.routers.syncthing.tls.certresolver=myresolver"

networks:
  reverse-proxy:
    external: true

volumes:
  syncthing_config:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/syncthing"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
  syncthing_music:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX:-SUBFAIL}/music"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
  syncthing_video:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX:-SUBFAIL}/video"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
  syncthing_books:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX:-SUBFAIL}/books"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
  syncthing_scratch:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX:-SUBFAIL}/scratch"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
  syncthing_camelot:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX:-SUBFAIL}/camelot"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
  syncthing_pictures:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX:-SUBFAIL}/pictures"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
  syncthing_data:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX:-SUBFAIL}/data"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
  syncthing_home:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX:-SUBFAIL}/home"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
  syncthing_bitwarden:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/bitwarden"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
