version: '2.2'
services:
  transmission:
    image: "haugene/transmission-openvpn"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
     - "9999:9999" #web proxy
    expose:
     - "9091"
    dns:
     - 8.8.8.8
    volumes:
     - transmission_completed_downloads:/data/complete
     - transmission_watch:/data/watch
     - transmission_incomplete_downloads:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=${VPN_OPENVPN_PROVIDER:-SUBFAIL}
      - OPENVPN_CONFIG=${VPN_OPENVPN_CONFIG:-SUBFAIL}
      - OPENVPN_USERNAME=${VPN_OPENVPN_USERNAME:-SUBFAIL}
      - OPENVPN_PASSWORD=${VPN_OPENVPN_PASSWORD:-SUBFAIL}
      - OPENVPN_OPTS=--pull-filter ignore ping
#      - CREATE_TUN_DEVICE=true
      - DROP_DEFAULT_ROUTE=true
      - TRANSMISSION_UMASK=0
      - TRANSMISSION_DOWNLOAD_DIR=/data/complete
      - TRANSMISSION_WATCH_DIR=/data/watch
      - TRANSMISSION_WATCH_DIR_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=50
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=3
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=1
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=false
      - TRANSMISSION_SPEED_LIMIT_DOWN=100
      - WEBPROXY_ENABLED=false
      - WEBPROXY_PORT=9999
      - TZ=${MY_TZ:-SUBFAIL}
      - VIRTUAL_PORT=9091
      - VIRTUAL_HOST=transmission.${DNS_SUFFIX:-local}
      - LETSENCRYPT_HOST=transmission.${DNS_SUFFIX:-local}
      - LETSENCRYPT_EMAIL=${LETS_ENC_EMAIL:-SUBFAIL}
      - TRANSMISSION_INCOMPLETE_DIR=/data/incomplete
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
    networks:
      - reverse-proxy
    labels:
      - "container_group=media"

      - "traefik.enable=true"

      - "traefik.docker.network=reverse-proxy" #needed if there are multiple networks attached to this container
      - "traefik.http.services.transmission.loadbalancer.server.port=9091" #needed if multiple ports are exposed

      # internal route for internal ips
      - "traefik.http.routers.transmission2.tls=true"
      - "traefik.http.routers.transmission2.tls.certresolver=myresolver"
      - "traefik.http.routers.transmission2.rule=Host(`transmission.${DNS_SUFFIX:-local}`) && HeadersRegexp(`X-Real-Ip`, `${TRAEFIK_INTERNAL_IPS:-SUBFAIL}`)"
      - "traefik.http.routers.transmission2.priority=100"
      - "traefik.http.routers.transmission2.entrypoints=websecure"
      # default route for external basic auth
      - "traefik.http.routers.transmission.tls=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.${DNS_SUFFIX:-local}`)"
      - "traefik.http.routers.transmission.priority=90"
      - "traefik.http.routers.transmission.middlewares=myauth"
      - "traefik.http.routers.transmission.entrypoints=websecure"
      - "traefik.http.routers.transmission.tls.certresolver=myresolver"

networks:
  reverse-proxy:
    external:
      name: reverse-proxy

volumes:
  transmission_completed_downloads:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX:-SUBFAIL}/scratch/!torrent"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
  transmission_incomplete_downloads:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX:-SUBFAIL}/scratch/!torrent/!incomplete"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
  transmission_watch:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX:-SUBFAIL}/scratch/!torrent/!watch"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}
