version: "3.3"

services:

  twingate:
    image: "twingate/connector:1"
    dns:
      - 192.168.3.2 # Primary internal DNS
      - 192.168.3.3 # Secondary DNS
    restart: unless-stopped
    network_mode: host
    environment:
      - "TWINGATE_NETWORK=${TWINGATE_NETWORK:-SUBFAIL}"
      - "TWINGATE_ACCESS_TOKEN=${TWINGATE_ACCESS_TOKEN:-SUBFAIL}"
      - "TWINGATE_REFRESH_TOKEN=${TWINGATE_REFRESH_TOKEN:-SUBFAIL}"
      
