version: "3.3"

services:

  twingate:
    image: "twingate/connector:1"
    restart: unless-stopped
    sysctls:
      - "net.ipv4.ping_group_range=0 2147483647"
    environment:
      - "TWINGATE_NETWORK=${TWINGATE_NETWORK:-SUBFAIL}"
      - "TWINGATE_ACCESS_TOKEN=${TWINGATE_ACCESS_TOKEN:-SUBFAIL}"   
      - "TWINGATE_REFRESH_TOKEN=${TWINGATE_REFRESH_TOKEN:-SUBFAIL}"

