version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${MY_TZ:-SUBFAIL}
      - SERVERURL=wireguard.${DNS_SUFFIX:-local} #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=172.69.0.101 #optional
#      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - wireguard_data:/config
      - /lib/modules:/lib/modules
    expose:
      - 51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      pihole_sub:
      reverse-proxy:
    labels:
      - "container_group=vpn"
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy" #needed if there are multiple networks attached to this container
      #udp 
      - "traefik.udp.routers.wireguard.entrypoints=wireguard"
      - "traefik.udp.routers.wireguard.service=wireguard"
      - "traefik.udp.services.wireguard.loadbalancer.server.port=51820"

  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    expose:
      - "80"
      - "443"
      - "53/tcp"
      - "53/udp"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      TZ: ${MY_TZ:-SUBFAIL}
    networks:
      pihole_sub:
        ipv4_address: 172.69.0.101

networks:
  pihole_sub:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.69.0.0/16
  reverse-proxy:
    external: true

volumes:
  wireguard_data:
    driver: "local"
    driver_opts:
      device: "${VOL_DEVICE_PREFIX_SSD:-SUBFAIL}/containers/wireguard"
      type: ${VOL_TYPE:-SUBFAIL}
      o: ${VOL_OPS:-SUBFAIL}

